### ISSUE TITLE
API метод для обновления рейтинга и счетчика

### ISSUE THREAD

**Issue by stleon** [stleon/voter#14]
Реализовать метод для обновления рейтинга (+1 или -1) и счетчика показов (+1) 2х пользователей со страницы голосований #11 

Например, фронт присылает json

```
{"hot": 12, "not": 3}
```

Это говорит о том, что надо для юзера с id 12 надо повысить рейтинг и счетчик показов на 1, а для юзера с id 3 - `рейтинг - 1` и `счетчик показов +1`

**Comment by singulared** [comment]
Для сохранения результатов голования, необходимо выполнить запрос на endpoint _/choices/[id]_
И передать выбранный пользователем uuid (#7) в виде json строки.

**Comment by singulared** [comment]
PUT /choices/11/
HTTP 200 OK
Allow: PUT, OPTIONS
Content-Type: application/json
Vary: Accept

``` json
"You vote was accepted"
```
